### ISSUE TITLE
Bug: Unable to run UI locally

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/tooling-curator#17]
When trying to develop locally using instructions for running the frontend, I can't get the UI to run for any commit from https://github.com/redhat-performance/tooling-curator/commit/cf62e35e949f528ca1e527a95f0a5eebd43c825b

Problem seems to be that https://github.com/redhat-performance/tooling-curator/blob/main/src/App.tsx#L56 does not return a JSON and instead we get an HTML page.

When trying to go back to https://github.com/redhat-performance/tooling-curator/commit/95a96dd121728f30964e6e0707addc1df1162e4d `npm run start` works.

![image](https://user-images.githubusercontent.com/11049799/232339477-b1c8a9e9-f7d0-4e66-b918-b9bc63cf5906.png)

**Comment by dustinblack** [comment]
I know the problem here. I'll take a look and find a fix.

**Comment by dustinblack** [comment]
Fixed with #20
